version: '3.4'

services:

  #API Gateway
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: API Gateway/Dockerfile
    ports:
      - "6000:80"
      - "7000:443"
    container_name: apigateway
    networks:
      - musify-network

#User Service
  userservice:
    depends_on:
      - userservicedatabase
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: User Service/Dockerfile
    ports:
      - "6001:80"
      - "7001:443"
    container_name: userservice
    networks:
      - musify-network
  userservicedatabase:
    image: mysql:5.7
    container_name: userservicedatabase
    ports:
      - "8001:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: "MusifyAuth"
      MYSQL_USER: "musify"
      MYSQL_PASSWORD: "musify"
    volumes:
      - dbuserdata:/var/lib/mysql1
    restart: always
    networks:
      - musify-network


#Playlist Service
  playlistservice:
    image: ${DOCKER_REGISTRY-}playlistservice
    depends_on: 
    - playlistservicedatabase
    build:
      context: .
      dockerfile: Playlist Service/Dockerfile
    ports:
      - "6002:80"
      - "7002:443"
    container_name: playlistservice
    networks:
      - musify-network
  playlistservicedatabase:
    image: mysql:5.7
    container_name: playlistservicedatabase
    ports:
      - "8002:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: "MusifyPlaylists"
      MYSQL_USER: "musify"
      MYSQL_PASSWORD: "musify"
    volumes:
      - dbplaylistdata:/var/lib/mysql2
    restart: always
    networks:
      - musify-network


#Song Service
  songservice:
    depends_on:
      - songservicedatabase
    image: ${DOCKER_REGISTRY-}songservice
    build:
      context: .
      dockerfile: Song Service/Dockerfile
    ports:
      - "6003:80"
      - "7003:443"
    container_name: songservice
    networks:
      - musify-network
  songservicedatabase:
    image: mysql:5.7
    container_name: songservicedatabase
    ports:
      - "8003:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: "MusifySongs"
      MYSQL_USER: "musify"
      MYSQL_PASSWORD: "musify"
    volumes:
      - dbsongdata:/var/lib/mysql3
    restart: always
    networks:
      - musify-network

  #RabbitMq 
  rabbitmq:
    container_name: rabbitmq
    image: lucifer8591/rabbitmq-server:3.7.17
    hostname: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
     - 15672
     - 5672
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    volumes:
      - ${DATA_PATH_HOST}/rabbitmq:/var/lib/rabbitmq/mnesia
    networks:
      - musify-network
networks:
  musify-network:

volumes:
    dbuserdata:
    dbplaylistdata:
    dbsongdata:
