version: '3.4'

services:

  #API Gateway
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: API Gateway/Dockerfile
    ports:
      - "6000:80"
      - "7000:443"
    container_name: apigateway
    networks:
      - musify-network

  #User Service
  userservice:
    depends_on:
      - userservicedatabase
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: User Service/Dockerfile
    ports:
      - "6001:80"
      - "7001:443"
    container_name: userservice
    networks:
      - musify-network
  userservicedatabase:
    image: mysql:5.7
    container_name: userservicedatabase
    ports:
      - "3306:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: "MusifyAuth"
      MYSQL_USER: "musify"
      MYSQL_PASSWORD: "musify"
    volumes:
      - dbdata:/var/lib/mysql2
    restart: always
    networks:
      - musify-network


  #Playlist Service
  playlistservice:
    image: ${DOCKER_REGISTRY-}playlistservice
    build:
      context: .
      dockerfile: Playlist Service/Dockerfile
    ports:
      - "6002:80"
      - "7002:443"
    container_name: playlistservice
    networks:
      - musify-network

networks:
  musify-network:

volumes:
    dbdata: